### ISSUE TITLE
Investigate i686 djgpp

### ISSUE THREAD

**Issue by hughobrien** [hughobrien/qemu-3dfx#8]
https://github.com/hughobrien/qemu-3dfx/blob/43cca8f4d360229158af9b6a1431fd8cf057389c/wrappers/3dfx/dxe/Makefile#L3

[Upstream uses i686](https://github.com/kjliew/qemu-3dfx/blob/0f2faac7ade56c666fd8ee0cf2c5dafec60631ec/wrappers/3dfx/dxe/Makefile#L3) but all I can find prebuilt is i586 from [here](https://github.com/andrewwutw/build-djgpp).

Building an i686 seems to be rarely referenced online:
1. https://web.archive.org/web/20050426002534/http://users.erols.com/praccompsol/djgpp/linux-x-djgpp-revised.txt
2. https://www.nathancoulson.com/proj/i586-pc-msdosdjgpp.php
3. https://www.delorie.com/howto/djgpp/linux-x-djgpp.html

Note i586 had MMX, so the benefits for i686 may not be substantial.

Investigate whether to build manually as described in the ancient sea scrolls above, or perhaps modify the build targets for the existing binary provider.

**Comment by hughobrien** [comment]
https://github.com/andrewwutw/build-djgpp/issues/45#issuecomment-1484010755

**Comment by hughobrien** [comment]
addded https://github.com/NixOS/nixpkgs/pull/237151/files#diff-b89bbef1212bc899b3c5ccdece3f7458f65deb127bfd12656999c5e8136af403R92

**Comment by graphixillusion** [comment]
@hughobrien I'm trying to build this in msys2 under Windows. How to get this i686 version to work with MSYS2?

**Comment by hughobrien** [comment]
I used two simple `sed` calls https://github.com/NixOS/nixpkgs/blob/2964b720de2cf30acd40d5f4d6c1034613c358ed/pkgs/development/compilers/djgpp/default.nix#L36

**Comment by graphixillusion** [comment]
> I used two simple `sed` calls https://github.com/NixOS/nixpkgs/blob/2964b720de2cf30acd40d5f4d6c1034613c358ed/pkgs/development/compilers/djgpp/default.nix#L36

I need to recompile everything i suppose

**Comment by graphixillusion** [comment]
@hughobrien I've tried to compile after change the script with this command:

`sed -i 's/i586/i686/g' 12.2.0`

but after a while i got this error:

```
../../gnu/gcc-12.20/gcc/system.h:782:30: error: expected identifier before string constant
  782 | #define abort() fancy_abort (__FILE__, __LINE__, __FUNCTION__)
      |                              ^~~~~~~~
../../gnu/gcc-12.20/gcc/system.h:782:30: error: expected ',' or '...' before string constant
../../gnu/gcc-12.20/gcc/system.h:782:30: error: expected identifier before string constant
  782 | #define abort() fancy_abort (__FILE__, __LINE__, __FUNCTION__)
      |                              ^~~~~~~~
../../gnu/gcc-12.20/gcc/system.h:782:30: error: expected ',' or '...' before string constant
make[2]: *** [Makefile:1143: diagnostic-color.o] Error 1
```
any idea?

**Comment by hughobrien** [comment]
there's two `sed`s you need - did you use both?

**Comment by graphixillusion** [comment]
@hughobrien i've used this as reference: 

https://github.com/andrewwutw/build-djgpp/issues/45#issuecomment-1484010755

It compiles ok under wsl/ubuntu but i did the exact same steps under mingw32 msys2 but it always fails at that point. The problem is that this procedure under linux build only executables for linux and not for windows. I need the exes: is there any way to build them under linux?

**Comment by hughobrien** [comment]
It might be a warning flag option that's different on msys. I had to disable format hardening. 

I suggest you compare the full build logs to see if gcc is being invoked differently.
